import { Candidate, Shift } from "@/types/domain";

export const demoShifts: Shift[] = [
  {
    id: "shift-001",
    title: "Night RN Coverage",
    unit: "ICU",
    facility: "Montreal General",
    role: "RN",
    startTime: new Date("2026-03-28T19:00:00"),
    endTime: new Date("2026-03-29T07:00:00"),
    requiredCertifications: ["BLS", "ICU"],
    priorityLevel: "HIGH",
    overtimeAllowed: true,
    unionRuleset: "standard-healthcare",
  },
  {
    id: "shift-002",
    title: "Day RN Coverage",
    unit: "ER",
    facility: "Montreal General",
    role: "RN",
    startTime: new Date("2026-03-29T07:00:00"),
    endTime: new Date("2026-03-29T19:00:00"),
    requiredCertifications: ["BLS", "ACLS"],
    priorityLevel: "CRITICAL",
    overtimeAllowed: true,
    unionRuleset: "standard-healthcare",
  },
  {
    id: "shift-003",
    title: "Evening RN Coverage",
    unit: "Med Surg",
    facility: "Montreal General",
    role: "RN",
    startTime: new Date("2026-03-29T15:00:00"),
    endTime: new Date("2026-03-29T23:00:00"),
    requiredCertifications: ["BLS"],
    priorityLevel: "MEDIUM",
    overtimeAllowed: false,
    unionRuleset: "standard-healthcare",
  },
];

export const demoShift = demoShifts[0];

export const demoCandidates: Candidate[] = [
  {
    id: "cand-001",
    name: "Sarah Lewis",
    role: "RN",
    certifications: ["BLS", "ICU", "ACLS"],
    unitsQualified: ["ICU", "ER"],
    facilitiesQualified: ["Montreal General"],
    weeklyHours: 32,
    overtimeHours: 2,
    seniorityScore: 78,
    recentAcceptRate: 84,
    recentResponseMinutes: 11,
    attendanceScore: 96,
    fatigueRisk: 0.21,
    channelPreferences: ["SMS", "APP", "IVR"],
    isAvailable: true,
    recentOutreachCount: 1,
    lastShiftEndedAt: new Date("2026-03-28T07:00:00"),
  },
  {
    id: "cand-002",
    name: "Miguel Torres",
    role: "RN",
    certifications: ["BLS", "ICU"],
    unitsQualified: ["ICU"],
    facilitiesQualified: ["Montreal General"],
    weeklyHours: 38,
    overtimeHours: 5,
    seniorityScore: 88,
    recentAcceptRate: 72,
    recentResponseMinutes: 16,
    attendanceScore: 91,
    fatigueRisk: 0.34,
    channelPreferences: ["APP", "SMS", "EMAIL"],
    isAvailable: true,
    recentOutreachCount: 3,
    lastShiftEndedAt: new Date("2026-03-28T06:00:00"),
  },
  {
    id: "cand-003",
    name: "Priya Patel",
    role: "RN",
    certifications: ["BLS", "ICU", "PALS"],
    unitsQualified: ["ICU", "Med Surg"],
    facilitiesQualified: ["Montreal General"],
    weeklyHours: 28,
    overtimeHours: 0,
    seniorityScore: 64,
    recentAcceptRate: 89,
    recentResponseMinutes: 8,
    attendanceScore: 94,
    fatigueRisk: 0.18,
    channelPreferences: ["SMS", "APP"],
    isAvailable: true,
    recentOutreachCount: 0,
    lastShiftEndedAt: new Date("2026-03-28T05:30:00"),
  },
  {
    id: "cand-004",
    name: "Daniel Brooks",
    role: "RN",
    certifications: ["BLS"],
    unitsQualified: ["ICU"],
    facilitiesQualified: ["Montreal General"],
    weeklyHours: 24,
    overtimeHours: 0,
    seniorityScore: 52,
    recentAcceptRate: 61,
    recentResponseMinutes: 20,
    attendanceScore: 86,
    fatigueRisk: 0.27,
    channelPreferences: ["IVR", "SMS"],
    isAvailable: true,
    recentOutreachCount: 2,
    lastShiftEndedAt: new Date("2026-03-28T04:00:00"),
  },
  {
    id: "cand-005",
    name: "Emma Chen",
    role: "RN",
    certifications: ["BLS", "Med Surg"],
    unitsQualified: ["Med Surg"],
    facilitiesQualified: ["Montreal General"],
    weeklyHours: 30,
    overtimeHours: 1,
    seniorityScore: 70,
    recentAcceptRate: 77,
    recentResponseMinutes: 14,
    attendanceScore: 93,
    fatigueRisk: 0.25,
    channelPreferences: ["SMS", "EMAIL"],
    isAvailable: false,
    recentOutreachCount: 1,
    lastShiftEndedAt: new Date("2026-03-28T06:30:00"),
  },
  {
    id: "cand-006",
    name: "Omar Khan",
    role: "RN",
    certifications: ["BLS", "ICU", "ACLS"],
    unitsQualified: ["ICU", "ER"],
    facilitiesQualified: ["Montreal General"],
    weeklyHours: 35,
    overtimeHours: 3,
    seniorityScore: 81,
    recentAcceptRate: 67,
    recentResponseMinutes: 10,
    attendanceScore: 88,
    fatigueRisk: 0.72,
    channelPreferences: ["APP", "SMS", "IVR"],
    isAvailable: true,
    recentOutreachCount: 4,
    lastShiftEndedAt: new Date("2026-03-28T09:30:00"),
  },
  {
    id: "cand-007",
    name: "Nadia Roy",
    role: "RN",
    certifications: ["BLS", "ACLS"],
    unitsQualified: ["ER"],
    facilitiesQualified: ["Montreal General"],
    weeklyHours: 26,
    overtimeHours: 0,
    seniorityScore: 60,
    recentAcceptRate: 82,
    recentResponseMinutes: 9,
    attendanceScore: 90,
    fatigueRisk: 0.16,
    channelPreferences: ["SMS", "APP", "EMAIL"],
    isAvailable: true,
    recentOutreachCount: 1,
    lastShiftEndedAt: new Date("2026-03-28T02:00:00"),
  },
];